// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NetworkBroken: typeof import('./src/components/NetworkBroken/index.vue')['default']
    SendCode: typeof import('./src/components/SendCode/index.vue')['default']
    SvgIcon: typeof import('./src/components/global/SvgIcon/index.vue')['default']
  }
}

export { }
