<template
  ><h1 id="内置功能" tabindex="-1"
    ><a class="header-anchor" href="#内置功能" aria-hidden="true">#</a> 内置功能</h1
  >
  <p
    >「天下武功，唯快不破」。只有快速完成需求，才有时间去学习更多、或在关键点上作一些优化。因此，脚手架为开发者内置了一些方便快捷的功能，解放开发者的双手，不用手动
    import 组件，Vue hooks 等。基于构建工具 webpack 或者 vite，集成了一些常用的插件。</p
  >
  <h2 id="自动导入自定义的组件" tabindex="-1"
    ><a class="header-anchor" href="#自动导入自定义的组件" aria-hidden="true">#</a>
    自动导入自定义的组件</h2
  >
  <p
    >直接在 template 写组件名即可，插件会帮你引入进来。<strong>注意别重名</strong>。借助
    <a
      href="https://github.com/antfu/unplugin-vue-components"
      target="_blank"
      rel="noopener noreferrer"
      >unplugin-vue-components<ExternalLinkIcon
    /></a>
    来实现，该插件支持 Vue2 和 Vue3。</p
  >
  <h3 id="vue-cli" tabindex="-1"
    ><a class="header-anchor" href="#vue-cli" aria-hidden="true">#</a> Vue CLI</h3
  >
  <div class="language-javascript ext-js line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #6A9955">// vue.config.js</span></span>
<span class="line"><span style="color: #4EC9B0">module</span><span style="color: #D4D4D4">.</span><span style="color: #4EC9B0">exports</span><span style="color: #D4D4D4"> = {</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">configureWebpack:</span><span style="color: #D4D4D4"> {</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #9CDCFE">plugins:</span><span style="color: #D4D4D4"> [</span></span>
<span class="line"><span style="color: #D4D4D4">      </span><span style="color: #DCDCAA">require</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&#39;unplugin-vue-components/webpack&#39;</span><span style="color: #D4D4D4">)({ </span><span style="color: #6A9955">/* options */</span><span style="color: #D4D4D4"> }),</span></span>
<span class="line"><span style="color: #D4D4D4">    ],</span></span>
<span class="line"><span style="color: #D4D4D4">  },</span></span>
<span class="line"><span style="color: #D4D4D4">}</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span
      ><br /></div></div
  ><h3 id="vite" tabindex="-1"
    ><a class="header-anchor" href="#vite" aria-hidden="true">#</a> Vite</h3
  >
  <div class="language-javascript ext-js line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #6A9955">// vite.config.ts</span></span>
<span class="line"><span style="color: #C586C0">import</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">Components</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">from</span><span style="color: #D4D4D4"> </span><span style="color: #CE9178">&#39;unplugin-vue-components/vite&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C586C0">export</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">default</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">defineConfig</span><span style="color: #D4D4D4">({</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">plugins:</span><span style="color: #D4D4D4"> [</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #DCDCAA">Components</span><span style="color: #D4D4D4">({}),</span></span>
<span class="line"><span style="color: #D4D4D4">  ],</span></span>
<span class="line"><span style="color: #D4D4D4">});</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span
      ><br /></div></div
  ><p
    >插件会生成一个自己组件路径的 <code>components.d.ts</code> 文件，具体可看这个 vue3 的<a
      href="https://github.com/vuejs/core/pull/3399"
      target="_blank"
      rel="noopener noreferrer"
      >issue types(defineComponent): support for expose component types<ExternalLinkIcon /></a
  ></p>
  <div class="language-typescript ext-ts line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #6A9955">// generated by unplugin-vue-components</span></span>
<span class="line"><span style="color: #6A9955">// We suggest you to commit this file into source control</span></span>
<span class="line"><span style="color: #6A9955">// Read more: https://github.com/vuejs/vue-next/pull/3399</span></span>
<span class="line"></span>
<span class="line"><span style="color: #569CD6">declare</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">module</span><span style="color: #D4D4D4"> </span><span style="color: #CE9178">&#39;vue&#39;</span><span style="color: #D4D4D4"> {</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #C586C0">export</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">interface</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">GlobalComponents</span><span style="color: #D4D4D4"> {</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #9CDCFE">NetworkBroken</span><span style="color: #D4D4D4">: </span><span style="color: #569CD6">typeof</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">import</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&#39;./src/components/NetworkBroken/index.vue&#39;</span><span style="color: #D4D4D4">)[</span><span style="color: #CE9178">&#39;default&#39;</span><span style="color: #D4D4D4">]</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #9CDCFE">SendCode</span><span style="color: #D4D4D4">: </span><span style="color: #569CD6">typeof</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">import</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&#39;./src/components/SendCode/index.vue&#39;</span><span style="color: #D4D4D4">)[</span><span style="color: #CE9178">&#39;default&#39;</span><span style="color: #D4D4D4">]</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #9CDCFE">SvgIcon</span><span style="color: #D4D4D4">: </span><span style="color: #569CD6">typeof</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">import</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&#39;./src/components/global/SvgIcon/index.vue&#39;</span><span style="color: #D4D4D4">)[</span><span style="color: #CE9178">&#39;default&#39;</span><span style="color: #D4D4D4">]</span></span>
<span class="line"><span style="color: #D4D4D4">  }</span></span>
<span class="line"><span style="color: #D4D4D4">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C586C0">export</span><span style="color: #D4D4D4"> { }</span></span>
<span class="line"></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span><br /><span
        class="line-number"
        >9</span
      ><br /><span class="line-number">10</span><br /><span class="line-number">11</span><br /><span
        class="line-number"
        >12</span
      ><br /><span class="line-number">13</span><br /><span class="line-number">14</span
      ><br /></div></div
  ><h3 id="用法示例" tabindex="-1"
    ><a class="header-anchor" href="#用法示例" aria-hidden="true">#</a> 用法示例</h3
  >
  <div class="language-vue ext-vue line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #808080">&lt;</span><span style="color: #569CD6">template</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #808080">&lt;</span><span style="color: #569CD6">div</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #808080">&lt;</span><span style="color: #4EC9B0">HelloWorld</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">msg</span><span style="color: #D4D4D4">=</span><span style="color: #CE9178">&quot;Hello Vue 3.0 + Vite&quot;</span><span style="color: #D4D4D4"> /</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #808080">&lt;/</span><span style="color: #569CD6">div</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #808080">&lt;/</span><span style="color: #569CD6">template</span><span style="color: #808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #808080">&lt;</span><span style="color: #569CD6">script</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #C586C0">export</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">default</span><span style="color: #D4D4D4"> {</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">name:</span><span style="color: #D4D4D4"> </span><span style="color: #CE9178">&#39;App&#39;</span></span>
<span class="line"><span style="color: #D4D4D4">}</span></span>
<span class="line"><span style="color: #808080">&lt;/</span><span style="color: #569CD6">script</span><span style="color: #808080">&gt;</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span><br /><span
        class="line-number"
        >9</span
      ><br /><span class="line-number">10</span><br /><span class="line-number">11</span
      ><br /></div></div
  ><p>自动转换成如下：</p>
  <div class="language-javascript ext-js line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #808080">&lt;</span><span style="color: #569CD6">template</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #808080">&lt;</span><span style="color: #569CD6">div</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #808080">&lt;</span><span style="color: #4EC9B0">HelloWorld</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">msg</span><span style="color: #D4D4D4">=</span><span style="color: #CE9178">&quot;Hello Vue 3.0 + Vite&quot;</span><span style="color: #D4D4D4"> </span><span style="color: #808080">/&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #808080">&lt;/</span><span style="color: #569CD6">div</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #808080">&lt;/</span><span style="color: #569CD6">template</span><span style="color: #808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #808080">&lt;</span><span style="color: #569CD6">script</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">import HelloWorld from &#39;./src/components/HelloWorld.vue&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #D4D4D4">export default </span><span style="color: #569CD6">{</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">name</span><span style="color: #D4D4D4">: </span><span style="color: #CE9178">&#39;App&#39;</span><span style="color: #D4D4D4">,</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">components</span><span style="color: #D4D4D4">: {</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #9CDCFE">HelloWorld</span></span>
<span class="line"><span style="color: #D4D4D4">  }</span></span>
<span class="line"><span style="color: #569CD6">}</span></span>
<span class="line"><span style="color: #808080">&lt;/</span><span style="color: #569CD6">script</span><span style="color: #808080">&gt;</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span><br /><span
        class="line-number"
        >9</span
      ><br /><span class="line-number">10</span><br /><span class="line-number">11</span><br /><span
        class="line-number"
        >12</span
      ><br /><span class="line-number">13</span><br /><span class="line-number">14</span><br /><span
        class="line-number"
        >15</span
      ><br /><span class="line-number">16</span><br /></div></div
  ><h3 id="插件默认配置" tabindex="-1"
    ><a class="header-anchor" href="#插件默认配置" aria-hidden="true">#</a> 插件默认配置</h3
  >
  <div class="language-javascript ext-js line-numbers-mode">
    <pre v-pre class="shiki" style="background-color: #1e1e1e"><code><span class="line"></span>
<span class="line"><span style="color: #DCDCAA">Components</span><span style="color: #D4D4D4">({</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// relative paths to the directory to search for components.</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">dirs:</span><span style="color: #D4D4D4"> [</span><span style="color: #CE9178">&#39;src/components&#39;</span><span style="color: #D4D4D4">],</span></span>
<span class="line"></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// valid file extensions for components.</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">extensions:</span><span style="color: #D4D4D4"> [</span><span style="color: #CE9178">&#39;vue&#39;</span><span style="color: #D4D4D4">],</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// search for subdirectories</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">deep:</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">true</span><span style="color: #D4D4D4">,</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// resolvers for custom components</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">resolvers:</span><span style="color: #D4D4D4"> [],</span></span>
<span class="line"></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// generate `components.d.ts` global declarations, </span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// also accepts a path for custom filename</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">dts:</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">false</span><span style="color: #D4D4D4">,</span></span>
<span class="line"></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// Allow subdirectories as namespace prefix for components.</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">directoryAsNamespace:</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">false</span><span style="color: #D4D4D4">,</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// Subdirectory paths for ignoring namespace prefixes</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// works when `directoryAsNamespace: true`</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">globalNamespaces:</span><span style="color: #D4D4D4"> [],</span></span>
<span class="line"></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// auto import for directives</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// default: `true` for Vue 3, `false` for Vue 2</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// Babel is needed to do the transformation for Vue 2, it&#39;s disabled by default for performance concerns.</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// To install Babel, run: `npm install -D @babel/parser @babel/traverse`</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">directives:</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">true</span><span style="color: #D4D4D4">,</span></span>
<span class="line"></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #6A9955">// filters for transforming targets</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">include:</span><span style="color: #D4D4D4"> [</span><span style="color: #D16969">/</span><span style="color: #D7BA7D">\.</span><span style="color: #D16969">vue</span><span style="color: #DCDCAA">$</span><span style="color: #D16969">/</span><span style="color: #D4D4D4">,</span><span style="color: #D16969"> /</span><span style="color: #D7BA7D">\.</span><span style="color: #D16969">vue</span><span style="color: #D7BA7D">\?</span><span style="color: #D16969">vue/</span><span style="color: #D4D4D4">],</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">exclude:</span><span style="color: #D4D4D4"> [</span><span style="color: #D16969">/</span><span style="color: #CE9178">[</span><span style="color: #D7BA7D">\\</span><span style="color: #D16969">/</span><span style="color: #CE9178">]</span><span style="color: #D16969">node_modules</span><span style="color: #CE9178">[</span><span style="color: #D7BA7D">\\</span><span style="color: #D16969">/</span><span style="color: #CE9178">]</span><span style="color: #D16969">/</span><span style="color: #D4D4D4">,</span><span style="color: #D16969"> /</span><span style="color: #CE9178">[</span><span style="color: #D7BA7D">\\</span><span style="color: #D16969">/</span><span style="color: #CE9178">]</span><span style="color: #D7BA7D">\.</span><span style="color: #D16969">git</span><span style="color: #CE9178">[</span><span style="color: #D7BA7D">\\</span><span style="color: #D16969">/</span><span style="color: #CE9178">]</span><span style="color: #D16969">/</span><span style="color: #D4D4D4">,</span><span style="color: #D16969"> /</span><span style="color: #CE9178">[</span><span style="color: #D7BA7D">\\</span><span style="color: #D16969">/</span><span style="color: #CE9178">]</span><span style="color: #D7BA7D">\.</span><span style="color: #D16969">nuxt</span><span style="color: #CE9178">[</span><span style="color: #D7BA7D">\\</span><span style="color: #D16969">/</span><span style="color: #CE9178">]</span><span style="color: #D16969">/</span><span style="color: #D4D4D4">],</span></span>
<span class="line"><span style="color: #D4D4D4">})</span></span>
<span class="line"></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span><br /><span
        class="line-number"
        >9</span
      ><br /><span class="line-number">10</span><br /><span class="line-number">11</span><br /><span
        class="line-number"
        >12</span
      ><br /><span class="line-number">13</span><br /><span class="line-number">14</span><br /><span
        class="line-number"
        >15</span
      ><br /><span class="line-number">16</span><br /><span class="line-number">17</span><br /><span
        class="line-number"
        >18</span
      ><br /><span class="line-number">19</span><br /><span class="line-number">20</span><br /><span
        class="line-number"
        >21</span
      ><br /><span class="line-number">22</span><br /><span class="line-number">23</span><br /><span
        class="line-number"
        >24</span
      ><br /><span class="line-number">25</span><br /><span class="line-number">26</span><br /><span
        class="line-number"
        >27</span
      ><br /><span class="line-number">28</span><br /><span class="line-number">29</span><br /><span
        class="line-number"
        >30</span
      ><br /><span class="line-number">31</span><br /><span class="line-number">32</span><br /><span
        class="line-number"
        >33</span
      ><br /></div></div
  ><div class="custom-container tip"
    ><p class="custom-container-title">提示</p>
    <p>unplugin-vue-components 用于常用的 UI 组件库的时候，比如 element-ui, vant 等，</p>
    <ul>
      <li
        >unplugin-vue-components 只支持模板上的引用，因此，挂载在 Vue.prototype
        上的属性和方法及指令，在使用的时候都得手动进行挂载。</li
      >
    </ul>
  </div>
  <h2 id="vue3" tabindex="-1"
    ><a class="header-anchor" href="#vue3" aria-hidden="true">#</a> Vue3</h2
  >
  <h3 id="setup-name-增强" tabindex="-1"
    ><a class="header-anchor" href="#setup-name-增强" aria-hidden="true">#</a> setup name 增强</h3
  >
  <p
    >在使用 Vue3 作为基础框架的时候，非常推荐大家使用更为快捷的 <code>setup</code> 写法。只需要在
    <code>script</code> 标签上加上 <code>setup</code> 属性，组件在编译的过程中代码运行的上下文是在
    <code>setup()</code> 函数中，无需 <code>return</code>，<code>template</code> 可直接使用。
    但在使用的时候，存在一个不方便的地方，即<strong>无法自定义 name</strong>。我们在使用 keep-alive
    是需要 name 的。而解决这个问题通常是，需要通过写两个 script 标签来解决，一个使用 setup，一个使用
    defineComponent，但这样不够优雅。如下：</p
  >
  <div class="language-javascript ext-js line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #808080">&lt;</span><span style="color: #569CD6">script</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">import </span><span style="color: #569CD6">{</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">defineComponent</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">}</span><span style="color: #D4D4D4"> from &#39;vue&#39;;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #D4D4D4">export default defineComponent(</span><span style="color: #569CD6">{</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">name</span><span style="color: #D4D4D4">: </span><span style="color: #CE9178">&#39;App&#39;</span></span>
<span class="line"><span style="color: #569CD6">}</span><span style="color: #D4D4D4">)</span></span>
<span class="line"><span style="color: #808080">&lt;/&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #808080">&lt;</span><span style="color: #569CD6">script</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">setup</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">// ...</span></span>
<span class="line"><span style="color: #808080">&lt;/</span><span style="color: #569CD6">script</span><span style="color: #808080">&gt;</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span><br /><span
        class="line-number"
        >9</span
      ><br /><span class="line-number">10</span><br /><span class="line-number">11</span
      ><br /></div></div
  ><p
    >可以借助
    <a
      href="https://github.com/cklwblove/unplugin-vue-setup-extend"
      target="_blank"
      rel="noopener noreferrer"
      >unplugin-vue-setup-extend<ExternalLinkIcon
    /></a>
    来实现。</p
  >
  <h3 id="vuecli" tabindex="-1"
    ><a class="header-anchor" href="#vuecli" aria-hidden="true">#</a> VueCLI</h3
  >
  <div class="language-javascript ext-js line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #4EC9B0">module</span><span style="color: #D4D4D4">.</span><span style="color: #4EC9B0">exports</span><span style="color: #D4D4D4"> = {</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">configureWebpack:</span><span style="color: #D4D4D4"> {</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #9CDCFE">plugins:</span><span style="color: #D4D4D4"> [</span></span>
<span class="line"><span style="color: #D4D4D4">      </span><span style="color: #DCDCAA">require</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&#39;@winner-fed/unplugin-vue-setup-extend/webpack&#39;</span><span style="color: #D4D4D4">).</span><span style="color: #DCDCAA">default</span><span style="color: #D4D4D4">({ </span><span style="color: #6A9955">/* options */</span><span style="color: #D4D4D4"> }),</span></span>
<span class="line"><span style="color: #D4D4D4">    ],</span></span>
<span class="line"><span style="color: #D4D4D4">  },</span></span>
<span class="line"><span style="color: #D4D4D4">}</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /></div></div
  ><h3 id="vite-1" tabindex="-1"
    ><a class="header-anchor" href="#vite-1" aria-hidden="true">#</a> Vite</h3
  >
  <div class="language-javascript ext-js line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #6A9955">// vite.config.js</span></span>
<span class="line"><span style="color: #C586C0">import</span><span style="color: #D4D4D4"> { </span><span style="color: #9CDCFE">defineConfig</span><span style="color: #D4D4D4">, </span><span style="color: #9CDCFE">Plugin</span><span style="color: #D4D4D4"> } </span><span style="color: #C586C0">from</span><span style="color: #D4D4D4"> </span><span style="color: #CE9178">&#39;vite&#39;</span></span>
<span class="line"><span style="color: #C586C0">import</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">vue</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">from</span><span style="color: #D4D4D4"> </span><span style="color: #CE9178">&#39;@vitejs/plugin-vue&#39;</span></span>
<span class="line"><span style="color: #C586C0">import</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">vueSetupExtend</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">from</span><span style="color: #D4D4D4"> </span><span style="color: #CE9178">&#39;@winner-fed/unplugin-vue-setup-extend&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C586C0">export</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">default</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">defineConfig</span><span style="color: #D4D4D4">({</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">plugins:</span><span style="color: #D4D4D4"> [</span><span style="color: #DCDCAA">vue</span><span style="color: #D4D4D4">(), </span><span style="color: #DCDCAA">vueSetupExtend</span><span style="color: #D4D4D4">()],</span></span>
<span class="line"><span style="color: #D4D4D4">})</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span
      ><br /></div></div
  ><h3 id="使用方式" tabindex="-1"
    ><a class="header-anchor" href="#使用方式" aria-hidden="true">#</a> 使用方式</h3
  >
  <div class="language-vue ext-vue line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #808080">&lt;</span><span style="color: #569CD6">template</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #808080">&lt;</span><span style="color: #569CD6">div</span><span style="color: #808080">&gt;</span><span style="color: #D4D4D4">hello world {{ </span><span style="color: #9CDCFE">a</span><span style="color: #D4D4D4"> }}</span><span style="color: #808080">&lt;/</span><span style="color: #569CD6">div</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #808080">&lt;/</span><span style="color: #569CD6">template</span><span style="color: #808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #808080">&lt;</span><span style="color: #569CD6">script</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">lang</span><span style="color: #D4D4D4">=</span><span style="color: #CE9178">&quot;ts&quot;</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">setup</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">name</span><span style="color: #D4D4D4">=</span><span style="color: #CE9178">&quot;App&quot;</span><span style="color: #808080">&gt;</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #569CD6">const</span><span style="color: #D4D4D4"> </span><span style="color: #4FC1FF">a</span><span style="color: #D4D4D4"> = </span><span style="color: #B5CEA8">1</span></span>
<span class="line"><span style="color: #808080">&lt;/</span><span style="color: #569CD6">script</span><span style="color: #808080">&gt;</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /></div></div
  ><h3 id="api-ref-reactive-torefs-等-自动导入" tabindex="-1"
    ><a class="header-anchor" href="#api-ref-reactive-torefs-等-自动导入" aria-hidden="true">#</a>
    API（ref，reactive，toRefs 等） 自动导入</h3
  >
  <p
    >setup 语法让我们不用再一个一个的把变量和方法都 return
    出去，就能在模板上使用，大大的解放了我们的双手。然而对于一些常用的组合式 API，比如
    ref、toRefs、reactive、watch等，还是每次都需要我们在页面上手动进行import。 我们可以通过
    <a
      href="https://github.com/antfu/unplugin-auto-import"
      target="_blank"
      rel="noopener noreferrer"
      >unplugin-auto-import<ExternalLinkIcon
    /></a>
    实现自动导入，无需 import 即可在文件里使用。</p
  >
  <h3 id="vue-cli-1" tabindex="-1"
    ><a class="header-anchor" href="#vue-cli-1" aria-hidden="true">#</a> Vue CLI</h3
  >
  <div class="language-javascript ext-js line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #6A9955">// vue.config.js</span></span>
<span class="line"><span style="color: #4EC9B0">module</span><span style="color: #D4D4D4">.</span><span style="color: #4EC9B0">exports</span><span style="color: #D4D4D4"> = {</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">configureWebpack:</span><span style="color: #D4D4D4"> {</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #9CDCFE">plugins:</span><span style="color: #D4D4D4"> [</span></span>
<span class="line"><span style="color: #D4D4D4">      </span><span style="color: #DCDCAA">require</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&#39;unplugin-auto-import/webpack&#39;</span><span style="color: #D4D4D4">)({ </span><span style="color: #6A9955">/* options */</span><span style="color: #D4D4D4"> }),</span></span>
<span class="line"><span style="color: #D4D4D4">    ],</span></span>
<span class="line"><span style="color: #D4D4D4">  },</span></span>
<span class="line"><span style="color: #D4D4D4">}</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span
      ><br /></div></div
  ><h3 id="vite-2" tabindex="-1"
    ><a class="header-anchor" href="#vite-2" aria-hidden="true">#</a> Vite</h3
  >
  <div class="language-javascript ext-js line-numbers-mode">
    <pre
      v-pre
      class="shiki"
      style="background-color: #1e1e1e"
    ><code><span class="line"><span style="color: #6A9955">// vite.config.js</span></span>
<span class="line"><span style="color: #C586C0">import</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">AutoImport</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">from</span><span style="color: #D4D4D4"> </span><span style="color: #CE9178">&#39;unplugin-auto-import/vite&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C586C0">export</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">default</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">defineConfig</span><span style="color: #D4D4D4">({</span></span>
<span class="line"><span style="color: #D4D4D4">  </span><span style="color: #9CDCFE">plugins:</span><span style="color: #D4D4D4"> [</span></span>
<span class="line"><span style="color: #D4D4D4">    </span><span style="color: #DCDCAA">AutoImport</span><span style="color: #D4D4D4">({ </span><span style="color: #6A9955">/* options */</span><span style="color: #D4D4D4"> }),</span></span>
<span class="line"><span style="color: #D4D4D4">  ],</span></span>
<span class="line"><span style="color: #D4D4D4">})</span></span>
<span class="line"></span></code></pre
    ><div class="line-numbers" aria-hidden="true"
      ><span class="line-number">1</span><br /><span class="line-number">2</span><br /><span
        class="line-number"
        >3</span
      ><br /><span class="line-number">4</span><br /><span class="line-number">5</span><br /><span
        class="line-number"
        >6</span
      ><br /><span class="line-number">7</span><br /><span class="line-number">8</span
      ><br /></div></div
  ><div class="custom-container tip"
    ><p class="custom-container-title">注意</p>
    <ul>
      <li>根目录下的 auto-imports.d.ts 文件是自动生成的。</li>
      <li
        >在没有 import 的情况下使用会导致 eslint 提示报错，脚手架已经通过在 eslintrc.js 安装插件
        <a href="https://github.com/antfu/vue-global-api" target="_blank" rel="noopener noreferrer"
          >vue-global-api<ExternalLinkIcon
        /></a>
        解决了这个问题</li
      >
    </ul>
  </div>
</template>
